language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t simeonch7/react-test -f ./client/Dockerfile.dev . ./client

script:
  - - docker run -e CI=true simeonch7/react-test npm test

after_success:
  - docker build -t simeonch7/multi-client ./client
  - docker build -t simeonch7/multi-nginx ./nginx
  - docker build -t simeonch7/multi-server ./server
  - docker build -t simeonch7/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" |docker login -u "%DOCKER_ID" --password-stdin
  - docker push simeonch7/multi-client
  - docker push simeonch7/multi-nginx
  - docker push simeonch7/multi-server
  - docker push simeonch7/multi-worker